development:
    adapter: postgresql
    database: uploader_development
    password: secret
    host: localhost
    encoding: unicode

test:
    adapter: postgresql
    database: uploader_test
    password: secret
    host: localhost
    encoding: unicode

production:
    adapter: postgresql
    database: uploader_development
    host: localhost
    encoding: unicode